name: notes_dashboard
description: Notes Dashboard
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  bloc: ^8.1.1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  local_storage_notes_api:
    path: packages/local_storage_notes_api
  notes_api:
    path: packages/notes_api
  notes_repository:
    path: packages/notes_repository
  flutter_staggered_grid_view: ^0.6.2

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mockingjay: ^0.3.0
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
flutter_intl:
  enabled: true
